name: Build & Deploy Node.js to Azure Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 16 LTS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install & build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: Archive for deployment
        run: |
          zip -r release.zip .  \
            -x "**/node_modules/**" \
            -x "**/.git/**" \
            -x "**/*.PublishSettings"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-package
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-package

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: webapp-myapp-001-koyakalyan
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
